name: homeautomation
description: A new Flutter application.
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.5
  speech_to_text: ^2.4.1
  avatar_glow: ^1.2.0
  fluttertoast: ^3.1.0
  material_design_icons_flutter: ^4.0.5345
  provider: ^4.0.3
  firebase_auth:
  cloud_firestore: ^0.13.7
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
    - assets/logo_size.jpg
    - assets/logo_50.jpeg
    - assets/logo_1_164x164.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-Black.ttf
        - asset: assets/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
    - family: Montserrat Bold
      fonts:
        - asset: assets/Montserrat/Montserrat-Bold.ttf
        - asset: assets/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700

